### ISSUE TITLE
Using statics breaks consumer expectations

### ISSUE THREAD

**Issue by bradleyayers** [tmorin/idomizer#2]
I ran into a bug that I eventually tracked down to idomizer, caused by using Incremental DOM's statics option in `elementOpen` are used by default.

My scenario is that I have two templates of the same structure, that only differ in attributes, e.g.:

**A:**

``` html
<path d="M4 …"></path>
```

and

**B:**

``` html
<path d="M9 …"></path>
```

(they're SVG paths)

In my application I alternate between the two SVGs based on some state:

``` javascript
if (someState) {
  renderA();
} else {
  renderB();
}
```

The problem is that the icon never changes from the one that was rendered first. This is due to the way the SVGs are being compiled to Incremental DOM, and the use of statics.

Currently it's compiled to:

```
elementOpen('path', null, ['d', 'M4 …', 'fill-rule', 'evenodd'], null);
elementClose('path');
```

but I want it to compile to:

```
elementOpen('path', null, null, 'd', 'M4 …', 'fill-rule', 'evenodd');
elementClose('path');
```

**Comment by tmorin** [comment]
Hi,

I will give you a quick response below, but it will be better for my understanding to see the source code of both the templates and the If statement.

> My scenario is that I have two templates of the same structure, that only differ in attributes, e.g.:

My first feeling is: because both templates are sharing the same structure and only differ in attributes, you should only have one template with dynamic attributes (c.f. http://tmorin.github.io/idomizer/#dynamic-attributes).

However, if you cannot use one template for both use cases, I guess you should try to specify a key (**tpl-key**, c.f. http://tmorin.github.io/idomizer/#iteration-with-the-tag-_each_ or http://google.github.io/incremental-dom/#demos/using-keys):

``` html
<path d="M4 …" tpl-key="'a constant'"></path>
```

or

``` html
<path d="M4 …" tpl-key="{{aDynamicValueWhichCanBeUUID}}"></path>
```

Finally, I never tested that, but may be the following snippet will work. The idea is to use the dynamic attributes with constant values.

A:

``` html
<path d="{{'M4 …'}}"></path>
```

B:

``` html
<path d="{{'M9 …'}}"></path>
```

Best regards

**Comment by bradleyayers** [comment]
In my scenario I'm generating an commonjs module with icons based on local `.svg` files that are exported from Sketch, so injecting the variable syntax isn't going to be compatible with that approach.

This is done via a webpack loader [pack-svgs.js](https://bitbucket.org/atlassian/atlaskit/src/c0ac9e1f620d5e2ef80760598e3179aae800b00a/packages/ak-icon/src/pack-svgs.js?at=master&fileviewer=file-view-default) that bundles all the icons in [icons/](https://bitbucket.org/atlassian/atlaskit/src/c0ac9e1f620d5e2ef80760598e3179aae800b00a/packages/ak-icon/src/icons/?at=master)

I suppose in my case it'd be useful to just have a config option to disable the template behaviour, and treat everything "as-is".

**Comment by tmorin** [comment]
Hi,

The version 0.5.3 handles a new option: **ignoreStaticAttributes**
- doc: https://tmorin.github.io/idomizer/typedef/index.html#static-typedef-OPTIONS
- unit test: https://github.com/tmorin/idomizer/blob/master/test/idomizer.spec.js#L204

Best regards,
